name: Sync

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 2 2 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    env:
      USER: ${{ github.repository_owner }}
      REPO_DATA: ${{ vars.REPO_DATA }}
      PATH_DATA: temp

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ env.USER }}
          repositories: ${{ env.REPO_DATA }}

      - name: Checkout DATA
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_DATA }}
          path: ${{ env.PATH_DATA }}
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Python Env
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Run scripts
        run: |
          pushd ${{ env.PATH_DATA }}
          pip install -r requirements.txt > /dev/null 2>&1 &&
          python src/run-export.py --data ./ --output ../ &&
          python src/run-stats.py --data ../ --output ../README.md
          popd

      - name: Set tag name
        id: tag
        run: |
          TAG="v$(date +'%Y.%m.%d')"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: "Automated monthly update"
          tag_name: ${{ steps.tag.outputs.tag_name }}
